### ISSUE TITLE
Script fails at muxing when attempting to use subprocess.py

### ISSUE THREAD

**Issue by emfolkerts** [SASUKE-DUCK/DV-HDR-Hybrid#1]
C:\Users\jdfol\Videos\DV-HDR-Hybrid>python dv.py -m 3 -o s01e01hybrid -dv Severance.S01E01.Good.News.About.Hell.REPACK.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.HEVC-TEPES.mkv -hdr s01e01hdr10_hdr10_slow.mp4
2023-12-12 10:52:13 [I] HYBRiD : by -∞WKS∞-#3982
2023-12-12 10:52:13 [I] HYBRiD : Required files: dovi_tool.exe, mkvmerge.exe, ffmpeg.exe
2023-12-12 10:52:13 [I] HYBRiD : Extracting Dolby Vision video and generating BIN DV Profile 8...
2023-12-12 10:52:13 [I] HYBRiD : Using default Dolby Vision extraction...
size=10248888kB time=00:57:14.51 bitrate=24445.6kbits/s speed=67.9x
2023-12-12 10:53:04 [I] HYBRiD : Converting P5 RPU to P8...
Reordering metadata... Done.
2023-12-12 10:53:36 [I] HYBRiD : Extraction complete.
2023-12-12 10:53:36 [I] HYBRiD : JSON file 'L6_8.1.json' generated successfully for HDR Mode.
Error: unknown field `length`, expected one of `mode`, `remove_cmv4`, `remove_mapping`, `min_pq`, `max_pq`, `active_area`, `remove`, `duplicate`, `scene_cuts`, `level6`, `level9`, `level11`, `level255`, `source_rpu`, `rpu_levels` at line 2 column 13
2023-12-12 10:53:36 [W] HYBRiD : Warning: RPU was not edited successfully!
2023-12-12 10:53:36 [I] HYBRiD : Extracting HDR10 video and determining FPS...
size= 9998500kB time=00:57:14.59 bitrate=23847.8kbits/s speed=62.5x
2023-12-12 10:54:31 [I] HYBRiD : Extraction complete.
2023-12-12 10:54:31 [I] HYBRiD : Video FPS: 24000/1001p
2023-12-12 10:54:31 [I] HYBRiD : Merging DV Profile 8 and HDR...
2023-12-12 10:54:31 [I] HYBRiD : RPU was not edited successfully. Using RPU.bin for injection.
Parsing RPU file...
Processing input video for frame order info...
Rewriting file with interleaved RPU NALs..
2023-12-12 10:55:55 [I] HYBRiD : Muxing...
Traceback (most recent call last):
  File "C:\Users\jdfol\Videos\DV-HDR-Hybrid\dv.py", line 222, in <module>
    subprocess.run(muxing_command)
  File "C:\Users\jdfol\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jdfol\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jdfol\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by SASUKE-DUCK** [comment]
you must add mkvmerge

**Comment by BlindCameraMan** [comment]
> you must add mkvmerge

It's in the folder with the script. I even re downloaded the exe just to be safe it gives the same error.

**Comment by BlindCameraMan** [comment]
Script is now working after dy.py was updated
